### PR TITLE
Disabling TOS Verification.

### PR DESCRIPTION
**Pull request by Boby360**
Temporarily disabling TOS Verification.
Pogo map has this feature built in via -tut so this is not necessary for the time being.

p.s. My first PR ;)

### CODE REVIEW

**Comment by badeanda** [comment]
Are you sure this disables TOS? It still says trying to accept... accepted

**Comment by Boby360** [comment]
Are you aware on how to properly install these changes?

**Comment by badeanda** [comment]
I'm actually not sure, long since i installed Pikaptcha :\

**Comment by Boby360** [comment]
This is a PR. Which means that this update isn't implemented yet. You have to get your files changed. and then run a command to install the changes. It actually took me quite alot of mucking around to find the right commands. I'm not very familar with pip, git, and python. i would update everything first. by doing "git pull" (or an updating variant)  then I think i did pip uninstall pikaptcha and then pip install C:\folder\folder  the folder target is the one with the setup.py and NOT the folder that contains the console.py, gmailv.py and etc etc.

Doing this essentially gets you the newest files (if they aren't up to date.) then deleting the files it installs (but still having the python files you want to edit) I then would manually copy the files i suggested altering (or just do the two tiny edits yourself) then installing those changes.

I hope iv made it crystal clear i'm not familiar with the best methods of doing all of this. I believe those are the commands i used to get everything operational.

**Comment by Boby360** [comment]
Hmm. Didn't have the intention of these other fork changes being updated here. oops. Anywho if this never gets approved id just use my fully functional fork (as of today) https://github.com/boby360/Pikaptcha

**Comment by neskk** [comment]
Just because you like `-tut` on RocketMap, why would you just comment some lines out? Why not provide a cmd line parameter for disabling TOS acceptance?
I also don't get why @sriyegna merged this as it is since two or three extra lines of code would have made this much better. You're just stripping away functionality that some people were still using...

**Comment by sriyegna** [comment]
Ah my bad. I thought people wanted that change. I'm not really working on pikaptcha anymore so I was just merging changes that didn't break pikaptcha. I'm on vacation but I can fix it in a week. Alternatively, if someone makes a PR, I'll review and merge it

**Comment by aguita** [comment]
I would say that it should be left out.  The ToS should not be accepted without using the hash keys.  Any account using 0.45 to accept ToS would be immediately flagged and has subsequent problems with catpchas.    As a result, the ToS should be improved to accept hash keys, or it should not be able to be done.

**Comment by Boby360** [comment]
@augita gets it. The thing is guys. I can't program. I found a fork that had all the right fixes. Made that one alteration. And ultimately made a functional release from something that was broken and was going to create a instantly banned  useless account. Obviously theres better ways to do it. No one else did. So I did. And alot of people. Benefited from it. Now there's pallet town which is just a fork of pikaptcha rebuilt in Java with a Gui and some good additions. Which is what it seems everyone uses now. Although pikaptcha works fine for now. (in my fork i most recently took out some symbols that apparently the account login method didn't like even though account creation did. Not sure if that was ever implemented) also I don't think the one alteration to the requirements taking out the old api was verified to have no issues or if it pulled in the requests that people have been having an issue with.

**Comment by neskk** [comment]
@boby360 Saying it wasn't functional is a overstatement since I'm still creating usable accounts and accepting TOS with Pikaptcha.

> The thing is guys. I can't program.

And now you have a PR on github 💃
I'll try to drop some support to use new API with hash-server in a PR and make TOS activation optional by using a parameter.
Please tells us what symbols in password generation are you talking about? `+`?

**Comment by aguita** [comment]
] does not appear to be allowed on account login, though it is allowed on account creation.   At one time, they had { } available on account creation, but they've removed those from the suggested passwords from what I can tell.

**Comment by sriyegna** [comment]
Back from vacay. What's the verdict on what needs to be done? I haven't followed any of the changes. If anyone would like to give me a rundown on discord, I can try and get it back up and running nicely.

**Comment by neskk** [comment]
@sriyegna I wanted to re-enable TOS activation but we need support for using HashKeys to enable new API. I'm even considering bringing the `-tut` code of RocketMap into Pikaptcha.
Second thing, tweak the "password symbols" merged PR to remove some chars that cause trouble.
Finally, test the timeout/sleep PR to check if 5 minutes works and merge it ;)

**Pull request merged**
