### PR TITLE
Added docker support with and without x11vnc

### PR DESCRIPTION
**Pull request by gregzetko**
Added 2 dockerfiles. The one named "Dockerfile" is made for headless use, and the one named "Dockerfile-manual" is made for manual captcha solving through VNC. If you are interested, then tell me here and I will document it.

### CODE REVIEW

**Comment by sriyegna** [comment]
Looks cool. I have no experience with docker. Am I correct in assuming this will not affect general users trying to run the script using the ReadMe?

I have no ability to test ATM so I hope it doesn't break anything lol.

**Comment by gregzetko** [comment]
@sriyegna nope, this does not affect any of the actual code. It is just a container that would run it. I will document it later.

**Comment by gregzetko** [comment]
alright I have added the documentation, but I'm terrible at formatting in markdown, so could you please fix it? Thanks!

**Comment by gregzetko** [comment]
Also I tested it, and it works, and it does not mess up anything that the regular users do now (except the README formatting) :+1:

**Comment by sriyegna** [comment]
Whoops sorry I took so long.

**Comment by gregzetko** [comment]
no problem :) thanks

**Pull request merged**
